### ISSUE TITLE
Reduce amount of requests needed

### ISSUE THREAD

**Issue by HaNdTriX** [cramforce/roadtrip#13]
Hey @cramforce 

Thanks for your awesome app. I really like its simplicity.

Did you know, that you can remove the [geocoding-server](https://roadtrip-api.glitch.me/) completely an gather all information needed in only one request? 

Thanks to the wikipedias [GeoData](https://www.mediawiki.org/wiki/Extension:GeoData) extension you can search directly by `lat` & `lng`.  If you are interested I can create a PR.

## Example

**Request**

```https://en.wikipedia.org/w/api.php?action=query&generator=geosearch&ggscoord=37.786952%7C-122.399523&ggsradius=1000&ggslimit=10&prop=coordinates%7Cpageimages%7Cextracts&explaintext=1&exintro=1&exlimit=10&origin=*&format=json```

**Response**

```json
{
  "batchcomplete": "",
  "query": {
    "pages": {
      "1544800": {
        "pageid": 1544800,
        "ns": 0,
        "title": "Cartoon Art Museum",
        "index": 0,
        "coordinates": [
          {
            "lat": 37.787088,
            "lon": -122.40094,
            "primary": "",
            "globe": "earth"
          }
        ],
        "thumbnail": {
          "source": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Location_map_San_Francisco_County.png/50px-Location_map_San_Francisco_County.png",
          "width": 50,
          "height": 43
        },
        "pageimage": "Location_map_San_Francisco_County.png",
        "extract": "The Cartoon Art Museum (CAM) is a California art museum that specializes in the art of comics and cartoons. It is the only museum in the Western United States dedicated to the preservation and exhibition of all forms of cartoon art. The permanent collection features some 7,000 pieces as of 2015, including original animation cels, comic book pages and sculptures.Until September 2015, the museum was located in the Yerba Buena Gardens cultural district of San Francisco, in the South of Market neighborhood. It reopened October 2017, in a new location in the Fisherman's Wharf area of San Francisco."
      },
      ...
  }
}
```

## Docs

https://www.mediawiki.org/wiki/API:Showing_nearby_wiki_information

<hr>

Best regards from Hamburg & HH.js 😉

Henrik

**Comment by cramforce** [comment]
I know I don't need the geocoding per se. The nearby API is already used. However, I do want to always start at a location with higher level information which works well with the geocoded query, while "nearby" articles are often super random things.

If there is a way to make a nearby query that starts with the current city (or part of city), before drilling down that would be perfect.

**Comment by HaNdTriX** [comment]
Thanks for the clarification. 

I am closing this issue since, the geosearch is not able to fulfill this need.
