### ISSUE TITLE
Reading materials not apparent

### ISSUE THREAD

**Issue by grahamperrin** [cramforce/roadtrip#6]
![2018-07-10 06 19 11](https://user-images.githubusercontent.com/192271/42490792-f8ba0084-8409-11e8-9a13-405e0b61c1d3.png)

![2018-07-10 06 21 00](https://user-images.githubusercontent.com/192271/42490791-f88ea4a2-8409-11e8-9bef-b04f2ffa9eea.png)

Reproducible in safe mode. 

Firefox on FreeBSD-CURRENT, 

```text
$ firefox --version ; pkg info firefox | grep Version
Mozilla Firefox 61.0
Version        : 61.0_3,1
$ pkg info waterfox | grep Version
Version        : 56.2.1.55_2
$ date ; uname -v
Tue 10 Jul 2018 06:23:46 BST
FreeBSD 12.0-CURRENT #7 r336136: Tue Jul 10 03:01:24 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
```

**Comment by grahamperrin** [comment]
OK, I had no loudspeakers plugged in. Didn't realise that the app is for reading audibly, not visibly. 

Maybe add a keyword such as 'aloud' or 'audible'? 

Thanks

**Comment by cramforce** [comment]
Thanks. Will see if this can be detected.

**Comment by grahamperrin** [comment]
Thanks. Now I a pop-up at the foot of the window, 

> Please make sure your volume is turned up!

– but it disappears quickly. Is it new?

**Comment by cramforce** [comment]
It is new. It could appear longer :)

There is no way to detect whether sound is actually off.

**Comment by grahamperrin** [comment]
Thanks :+1: 

Personally, I'd like it to remain visible until clicked. 

On the other hand, some users might react badly to anything even vaguely resembling a banner; might treat it as intrusive or nagging. 

Whatever you think is best :-)
