### ISSUE TITLE
Can't find location with some browsers/platforms

### ISSUE THREAD

**Issue by grahamperrin** [cramforce/roadtrip#7]
With a clean profile, and allowing the application to access my location: 

![2018-07-10 06 34 03](https://user-images.githubusercontent.com/192271/42491308-4398f5d6-840c-11e8-926a-725f24823b81.png)

https://www.waterfoxproject.org/

Waterfox 56.2.1 on FreeBSD-CURRENT, 

```text
$ pkg info waterfox | grep Version
Version        : 56.2.1.55_2
$ date ; uname -v
Tue 10 Jul 2018 06:23:46 BST
FreeBSD 12.0-CURRENT #7 r336136: Tue Jul 10 03:01:24 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
```

**Comment by cramforce** [comment]
Please debug this yourself and send a PR once you have a solution. Closing for now.

**Comment by grahamperrin** [comment]
https://www.reddit.com/comments/8xt831/-/e27d3bg/ tl;dr not specific to Waterfox. 

The issue is reproducible, sometimes with different symptoms, with Firefox on Linux (Kubuntu); the view of the map might change but speech never begins. 

I'm not good with pull requests (sorry, not a coder) … first, let's see whether an explanation can be found.

**Comment by grahamperrin** [comment]
### Waterfox

At <https://www.reddit.com/comments/8xt831/-/e2aekc2/> from the Founder: 

> Waterfox on Windows and macOS uses the operating systems location function. On linux it's provided by GPSD `geo.provider.use_gpsd`, assuming you have it set up. There is no Mozilla Location Service fallback.

https://stackoverflow.com/a/36167214/38108 suggests: 

> … it should be possible to write an extension to fake the GPS coordinates, …

– I'll not pursue that. For me, it's enough to have the application working in Firefox (on FreeBSD-CURRENT).  

### Firefox on Linux

> … the view of the map might change but speech never begins. …

I'll leave that unexplained :-)

**Comment by grahamperrin** [comment]
The same problem with Firefox, Waterfox and LastPass on Android. 

Google Chrome on the same handset (OnePlus 2) is OK.
