### ISSUE TITLE
Language selection feature

### ISSUE THREAD

**Issue by sunfudge** [cramforce/roadtrip#8]
Would be great to be able to select reading the articles in different languages!

Thanks

**Comment by YBadiss** [comment]
I just did a quick test for french, there's three parts:

- wikipedia: replace `en` by the standard 2 letter code of your language (e.g. `fr`)
- text to speech: the api supports changing the language through the `lang` property, which expects a BCP 47 language tag (e.g. `en-US`)
- welcome message: there is a welcome message which should be translated in supported languages

The easiest is probably a map, something like

```javascript
{
  'English (US)': {'wiki_tag': 'en', 'speech_tag': 'en-US', 'welcome_msg': 'Welcome to your road trip.'},
  'English (UK)': {'wiki_tag': 'en', 'speech_tag': 'en-GB', 'welcome_msg': 'Welcome to your road trip.'},
  'Français (CA)': {'wiki_tag': 'fr', 'speech_tag': 'fr-CA', 'welcome_msg': 'Bienvenue dans votre voyage.'}
}
```

**Comment by frafra** [comment]
This issue can be closed. Thank you!
