### ISSUE TITLE
[Error Speaking] : not handeled

### ISSUE THREAD

**Issue by mohitp3** [cramforce/roadtrip#9]
![image](https://user-images.githubusercontent.com/20501966/42506424-827f0f12-845f-11e8-80e6-0ecba4f70965.png)

**Comment by cramforce** [comment]
Was there an actual problem?

**Comment by mohitp3** [comment]
while checking the app in desktop , when clicked on the start trip button . it is showing these error . 
seems like i didn't have sound driver installed so it is throwing this error
